### PR TITLE
Fix bug #10 - lints not working when using EquatableMixin

### LINKED ISSUE #10: Not working when using EquatableMixin
Hey, thanks for your work. This lint is really useful, but it would be even better if mixins were also checked. 

**Description**
Lacking of the fields in a props is not reported if EquatableMixin is used instead of a class extension.

**Steps To Reproduce**

Non of this are reported.
```dart
import 'package:equatable/equatable.dart';

class FieldNotInPropsMixinExample with EquatableMixin {
  const FieldNotInPropsMixinExample({this.field});

  // A lint will appear here because field is not in not in props
  final String? field;

  @override
  List<Object?> get props => [];
}

class NoFieldToAddToPropsMixinExample extends FieldNotInPropsMixinExample {
  const NoFieldToAddToPropsMixinExample();
}

class OtherFieldToAddToPropsMixinExample extends FieldNotInPropsMixinExample {
  const OtherFieldToAddToPropsMixinExample({this.newField});

  final String? newField;

  @override
  List<Object?> get props => super.props..addAll([]);
}

```

**Expected Behavior**
It should be reported just as example show_a_lint_when_a_field_is_not_in_props.dart

### PR DESCRIPTION
**Pull request by jpauly-dev**
## Description

Fix #10

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [X] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

### CODE REVIEW

File: lib/src/lints/missing_field_in_equatable_props/helpers/add_equatable_class_field_declaration_listener.dart [hunk 1]
```diff
@@ -38,11 +38,14 @@ extension AddEquatableClassFieldDeclarationListener on LintRuleNodeRegistry {
...
+        final element = superType.element;
+        return (element.name == 'EquatableMixin' ||
+                element.name == 'Equatable') &&
+            element.librarySource.uri.toString().contains('package:equatable/');
+      });
 
-      if (!typeChecker.isAssignableFromType(classType)) {
+      if (!hasEquatable) {
         return;
       }
```
Comment (MaximeRougieux) [inline lib/src/lints/missing_field_in_equatable_props/helpers/add_equatable_class_field_declaration_listener.dart]: I think it's better if we keep using TypeChecker as it abstracts a lot of complexity from the analyzer here, did you try something like this ?

```dart
const mixinTypeChecker =
    TypeChecker.fromName('EquatableMixin', packageName: 'equatable');
const classTypeChecker =
    TypeChecker.fromName('Equatable', packageName: 'equatable');
final classType = classElement.thisType;

final isEquatable = mixinTypeChecker.isAssignableFromType(classType) ||
    classTypeChecker.isAssignableFromType(classType);

if (!isEquatable) {
  return;
}
```

Comment (jpauly-dev) [reply lib/src/lints/missing_field_in_equatable_props/helpers/add_equatable_class_field_declaration_listener.dart]: You're right. This solution works with all the examples.

**Review by MaximeRougieux — APPROVED** [review]

**Comment by MaximeRougieux** [comment]
Thanks @jpauly-dev, and sorry for the long time before review!
